import { GalleryImage } from '@/features/gallery-management/components/types/gallery'

export async function getExhibitionImages(): Promise<GalleryImage[]> {
  return [
    {
      url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/exhibition/3%20-%20Amore.webp',
      alt: 'Amore III - exhibition photograph',
      name: 'Amore III',
      physicalWidth: 24,
      physicalHeight: 30.5,
      material: 'silver gelatin print on baryta paper',
      exhibition: 'Amore • Galerie Borssenanger • 2024',
    },
    {
      url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/exhibition/4%20-%20Lichtbildnerei.webp',
      alt: 'Covid-19 - exhibition photograph',
      name: 'Covid-19',
      physicalWidth: 30,
      physicalHeight: 40,
      material: 'silver gelatin print on baryta paper',
      exhibition: 'Lichtbildnerei • Tankstellenprojektraum • 2023',
    },
    {
      url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/exhibition/5%20-%20Lichtbildnerei.webp',
      alt: 'an expression of wealth - exhibition photograph',
      name: 'an expression of wealth',
      physicalWidth: 30,
      physicalHeight: 40,
      material: 'silver gelatin print on baryta paper',
      exhibition: 'Lichtbildnerei • Tankstellenprojektraum • 2023',
    },
    {
      url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/exhibition/6%20-%20Lichtbildnerei.webp',
      alt: 'do a kickflip - exhibition photograph',
      name: 'do a kickflip',
      physicalWidth: 50,
      physicalHeight: 60,
      material: 'silver gelatin print on baryta paper',
      exhibition: 'Platz da! • Tankstellenprojektraum • 2022',
    },
    {
      url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/exhibition/2%20-%20Amore.webp',
      alt: 'Europa - exhibition photograph',
      name: 'Europa',
      physicalWidth: 18,
      physicalHeight: 24,
      material: 'silver gelatin print on panchromatic film',
      exhibition: 'Amore Europa • Galerie Borssenanger • 2025',
    },
    {
      url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/exhibition/25%20-%20Momentum.webp',
      alt: 'Industrie und Landschaft des Bezirkes Karl-Marx-Stadt - exhibition photograph',
      name: 'Industrie und Landschaft - Karl-Marx-Stadt',
      physicalWidth: 24,
      physicalHeight: 29.7,
      material: 'silver gelatin print on orwo document paper',
      exhibition: 'Momentum x Betrieb.kollektiv • Momentum • 2025',
    },
    {
      url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/exhibition/28%20-%20Best%20of%20II%20-%20Visitors%20Choise.webp',
      alt: 'sinteză - mixed media installation',
      name: 'sinteză',
      material: 'Mixed media installation',
      exhibition: 'Best of II - Visitors Choice • Museum Gunzenhauser • 2025',
    },
    {
      url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/exhibition/29%20-%20Best%20of%20II%20-%20Visitors%20Choise.webpn',
      alt: 'self potrait - photogram artwork',
      name: 'self potrait',
      physicalWidth: 108,
      physicalHeight: 230,
      material: 'photogram on baryta paper',
      exhibition: 'Best of II - Visitors Choice • Museum Gunzenhauser • 2025',
    },
  ]
}
