import { GalleryImage } from '@/types/gallery'

export async function getExhibitionImages(): Promise<GalleryImage[]> {
  return [
    {
      url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765802744/portfolio/exhibition/3_-_Amore.webp',
      alt: 'Amore III - exhibition photograph',
      name: 'Amore III',
      physicalWidth: 24,
      physicalHeight: 30.5,
      material: 'silver gelatin print on baryta paper',
      exhibition: 'Amore • Galerie Borssenanger • 2024',
    },
    {
      url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765802754/portfolio/exhibition/4_-_Lichtbildnerei.webp',
      alt: 'Covid-19 - exhibition photograph',
      name: 'Covid-19',
      physicalWidth: 30,
      physicalHeight: 40,
      material: 'silver gelatin print on baryta paper',
      exhibition: 'Lichtbildnerei • Tankstellenprojektraum • 2023',
    },
    {
      url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765802763/portfolio/exhibition/5_-_Lichtbildnerei.webp',
      alt: 'an expression of wealth - exhibition photograph',
      name: 'an expression of wealth',
      physicalWidth: 30,
      physicalHeight: 40,
      material: 'silver gelatin print on baryta paper',
      exhibition: 'Lichtbildnerei • Tankstellenprojektraum • 2023',
    },
    {
      url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/v1765809039/6_-_Lichtbildnerei_d5lfpm.webp',
      alt: 'do a kickflip - exhibition photograph',
      name: 'do a kickflip',
      physicalWidth: 50,
      physicalHeight: 60,
      material: 'silver gelatin print on baryta paper',
      exhibition: 'Platz da! • Tankstellenprojektraum • 2022',
    },
    {
      url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765802721/portfolio/exhibition/2_-_Amore.webp',
      alt: 'Europa - exhibition photograph',
      name: 'Europa',
      physicalWidth: 18,
      physicalHeight: 24,
      material: 'silver gelatin print on panchromatic film',
      exhibition: 'Amore Europa • Galerie Borssenanger • 2025',
    },
    {
      url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765802726/portfolio/exhibition/25_-_Momentum.webp',
      alt: 'Industrie und Landschaft des Bezirkes Karl-Marx-Stadt - exhibition photograph',
      name: 'Industrie und Landschaft - Karl-Marx-Stadt',
      physicalWidth: 24,
      physicalHeight: 29.7,
      material: 'silver gelatin print on orwo document paper',
      exhibition: 'Momentum x Betrieb.kollektiv • Momentum • 2025',
    },
    {
      url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765802731/portfolio/exhibition/28_-_Best_of_II_-_Visitors_Choise.webp',
      alt: 'sinteză - mixed media installation',
      name: 'sinteză',
      material: 'Mixed media installation',
      exhibition: 'Best of II - Visitors Choice • Museum Gunzenhauser • 2025',
    },
    {
      url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765802736/portfolio/exhibition/29_-_Best_of_II_-_Visitors_Choise.webp',
      alt: 'self potrait - photogram artwork',
      name: 'self potrait',
      physicalWidth: 108,
      physicalHeight: 230,
      material: 'photogram on baryta paper',
      exhibition: 'Best of II - Visitors Choice • Museum Gunzenhauser • 2025',
    },
  ]
}
