import { GalleryImage } from '../components/types/gallery'
import { getImageUrl } from '../../../config/blob'

// Static gallery data extracted from PDF
const humanImages: GalleryImage[] = [
  {
    url: getImageUrl('gallery/human/7 - Human.webp'),
    alt: 'hiking',
    width: 800,
    height: 1000,
    name: 'hiking',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/human/8 - Human.webp'),
    alt: 'summer',
    width: 800,
    height: 1000,
    name: 'summer',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/human/13 - Human.webp'),
    alt: 'hungry',
    width: 800,
    height: 1000,
    name: 'hungry',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/human/15 - Human.webp'),
    alt: 'bogey',
    width: 800,
    height: 1000,
    name: 'bogey',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/human/23 - Human.webp'),
    alt: 'dieter',
    width: 800,
    height: 1200,
    name: 'dieter',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/human/24 - Human.webp'),
    alt: 'another day',
    width: 800,
    height: 1200,
    name: 'another day',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/human/26 - Human.webp'),
    alt: 'thomas',
    width: 800,
    height: 1200,
    name: 'thomas',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  // Former inverted image integrated into human gallery
  {
    url: getImageUrl('gallery/human/20 - Human.webp'),
    alt: 'waiting',
    width: 800,
    height: 1000,
    name: 'waiting',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
]

const nonHumanImages: GalleryImage[] = [
  {
    url: getImageUrl('gallery/non-human/9 - No Human.webp'),
    alt: 'flowers',
    width: 800,
    height: 1000,
    name: 'flowers',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/non-human/10 - No Human.webp'),
    alt: 'mood II',
    width: 800,
    height: 1000,
    name: 'mood II',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/non-human/11 - No Human.webp'),
    alt: 'curtains II',
    width: 800,
    height: 1000,
    name: 'curtains II',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/non-human/12 - No Human.webp'),
    alt: 'bubbles',
    width: 800,
    height: 1000,
    name: 'bubbles',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/non-human/14 - No Human.webp'),
    alt: 'be careful',
    width: 800,
    height: 1000,
    name: 'be careful',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/non-human/17 - No Human.webp'),
    alt: 'humans',
    width: 800,
    height: 1200,
    name: 'humans',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/non-human/18 - No Human.webp'),
    alt: 'mood',
    width: 800,
    height: 1000,
    name: 'mood',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/non-human/19 - No Human.webp'),
    alt: 'curtains',
    width: 800,
    height: 1000,
    name: 'curtains',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/non-human/21 - No Human.webp'),
    alt: 'Dark flowers',
    width: 800,
    height: 1080,
    name: 'Dark flowers',
    physicalWidth: 31,
    physicalHeight: 42,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/non-human/22 - No Human.jpg'),
    alt: 'arrangement',
    width: 800,
    height: 1080,
    name: 'arrangement',
    physicalWidth: 80,
    physicalHeight: 108,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: getImageUrl('gallery/non-human/27 - No Human.webp'),
    alt: 'alex',
    width: 800,
    height: 1000,
    name: 'alex',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
]

// Main function to get gallery images
export const getGalleryImages = async (type: 'human' | 'non-human'): Promise<GalleryImage[]> => {
  switch (type) {
    case 'human':
      return humanImages
    case 'non-human':
      return nonHumanImages
    default:
      return []
  }
}
