import { GalleryImage } from '../../../types/gallery'

// Static gallery data extracted from PDF
const humanImages: GalleryImage[] = [
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/human/7%20-%20Human.webp',
    alt: 'hiking',
    width: 800,
    height: 1000,
    name: 'hiking',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/human/8%20-%20Human.webp',
    alt: 'summer',
    width: 800,
    height: 1000,
    name: 'summer',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/human/13%20-%20Human.webp',
    alt: 'hungry',
    width: 800,
    height: 1000,
    name: 'hungry',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/human/15%20-%20Human.webp',
    alt: 'bogey',
    width: 800,
    height: 1000,
    name: 'bogey',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/human/23%20-%20Human.webp',
    alt: 'dieter',
    width: 800,
    height: 1200,
    name: 'dieter',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/human/24%20-%20Human.webp',
    alt: 'another day',
    width: 800,
    height: 1200,
    name: 'another day',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/human/26%20-%20Human.webp',
    alt: 'thomas',
    width: 800,
    height: 1200,
    name: 'thomas',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  // Former inverted image integrated into human
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/human/20%20-%20Human.webp',
    alt: 'waiting',
    width: 800,
    height: 1000,
    name: 'waiting',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
]

const nonHumanImages: GalleryImage[] = [
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/9%20-%20No%20Human.webp',
    alt: 'flowers',
    width: 800,
    height: 1000,
    name: 'flowers',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/10%20-%20No%20Human.webp',
    alt: 'mood II',
    width: 800,
    height: 1000,
    name: 'mood II',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/11%20-%20No%20Human.webp',
    alt: 'curtains II',
    width: 800,
    height: 1000,
    name: 'curtains II',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/12%20-%20No%20Human.webp',
    alt: 'bubbles',
    width: 800,
    height: 1000,
    name: 'bubbles',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/14%20-%20No%20Human.webp',
    alt: 'be careful',
    width: 800,
    height: 1000,
    name: 'be careful',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/17%20-%20No%20Human.webp',
    alt: 'humans',
    width: 800,
    height: 1200,
    name: 'humans',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/22%20-%20No%20Human.webp',
    alt: 'arrangement',
    width: 800,
    height: 1080,
    name: 'arrangement',
    physicalWidth: 80,
    physicalHeight: 108,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/27%20-%20No%20Human.webp',
    alt: 'alex',
    width: 800,
    height: 1000,
    name: 'alex',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/18%20-%20No%20Human.webp',
    alt: 'mood',
    width: 800,
    height: 1000,
    name: 'mood',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/19%20-%20No%20Human.webp',
    alt: 'curtains',
    width: 800,
    height: 1000,
    name: 'curtains',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
  {
    url: 'https://ckr77j2dv5dhtnev.public.blob.vercel-storage.com/non-human/21%20-%20No%20Human.webp',
    alt: 'Dark flowers',
    width: 800,
    height: 1080,
    name: 'Dark flowers',
    physicalWidth: 31,
    physicalHeight: 42,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
  },
]

// Main function to get gallery images
export const getGalleryImages = async (type: 'human' | 'non-human'): Promise<GalleryImage[]> => {
  switch (type) {
    case 'human':
      return humanImages
    case 'non-human':
      return nonHumanImages
    default:
      return []
  }
}
