import { GalleryImage } from '../../../types/gallery'

// Gallery data with Cloudinary URLs and blur placeholders
const humanImages: GalleryImage[] = [
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800236/portfolio/human/hiking.webp',
    alt: 'hiking',
    width: 800,
    height: 1000,
    name: 'hiking',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800236/portfolio/human/hiking.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800253/portfolio/human/summer.webp',
    alt: 'summer',
    width: 800,
    height: 1000,
    name: 'summer',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800253/portfolio/human/summer.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800268/portfolio/human/hungry.webp',
    alt: 'hungry',
    width: 800,
    height: 1000,
    name: 'hungry',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800268/portfolio/human/hungry.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800284/portfolio/human/bogey.webp',
    alt: 'bogey',
    width: 800,
    height: 1000,
    name: 'bogey',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800284/portfolio/human/bogey.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800304/portfolio/human/dieter.webp',
    alt: 'dieter',
    width: 800,
    height: 1200,
    name: 'dieter',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800304/portfolio/human/dieter.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800309/portfolio/human/another_day.webp',
    alt: 'another day',
    width: 800,
    height: 1200,
    name: 'another day',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800309/portfolio/human/another_day.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800314/portfolio/human/thomas.webp',
    alt: 'thomas',
    width: 800,
    height: 1200,
    name: 'thomas',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800314/portfolio/human/thomas.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800318/portfolio/human/waiting.webp',
    alt: 'waiting',
    width: 800,
    height: 1000,
    name: 'waiting',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800318/portfolio/human/waiting.webp',
  }
]

const nonHumanImages: GalleryImage[] = [
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800323/portfolio/non-human/flowers.webp',
    alt: 'flowers',
    width: 800,
    height: 1000,
    name: 'flowers',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800323/portfolio/non-human/flowers.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800340/portfolio/non-human/mood_II.webp',
    alt: 'mood II',
    width: 800,
    height: 1000,
    name: 'mood II',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800340/portfolio/non-human/mood_II.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800356/portfolio/non-human/curtains_II.webp',
    alt: 'curtains II',
    width: 800,
    height: 1000,
    name: 'curtains II',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800356/portfolio/non-human/curtains_II.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800373/portfolio/non-human/bubbles.webp',
    alt: 'bubbles',
    width: 800,
    height: 1000,
    name: 'bubbles',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800373/portfolio/non-human/bubbles.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800391/portfolio/non-human/be_careful.webp',
    alt: 'be careful',
    width: 800,
    height: 1000,
    name: 'be careful',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800391/portfolio/non-human/be_careful.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800406/portfolio/non-human/humans.webp',
    alt: 'humans',
    width: 800,
    height: 1200,
    name: 'humans',
    physicalWidth: 18,
    physicalHeight: 24,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800406/portfolio/non-human/humans.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800411/portfolio/non-human/arrangement.webp',
    alt: 'arrangement',
    width: 800,
    height: 1080,
    name: 'arrangement',
    physicalWidth: 80,
    physicalHeight: 108,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800411/portfolio/non-human/arrangement.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800433/portfolio/non-human/alex.webp',
    alt: 'alex',
    width: 800,
    height: 1000,
    name: 'alex',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800433/portfolio/non-human/alex.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765807344/portfolio/non-human/mood.webp',
    alt: 'mood',
    width: 800,
    height: 1000,
    name: 'mood',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765807344/portfolio/non-human/mood.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800459/portfolio/non-human/curtains.webp',
    alt: 'curtains',
    width: 800,
    height: 1000,
    name: 'curtains',
    physicalWidth: 40,
    physicalHeight: 50,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800459/portfolio/non-human/curtains.webp',
  },
  {
    url: 'https://res.cloudinary.com/dnnnchnqv/image/upload/f_auto,q_auto/v1765800478/portfolio/non-human/Dark_flowers.webp',
    alt: 'Dark flowers',
    width: 800,
    height: 1080,
    name: 'Dark flowers',
    physicalWidth: 31,
    physicalHeight: 42,
    unit: 'cm',
    material: 'silver gelatin print on baryta paper',
    blurDataUrl: 'https://res.cloudinary.com/dnnnchnqv/image/upload/e_blur:1000,w_10,q_auto:low,f_webp/f_auto,q_auto/v1765800478/portfolio/non-human/Dark_flowers.webp',
  }
]

// Individual functions for each gallery type
export const getHumanImages = async (): Promise<GalleryImage[]> => {
  return humanImages
}

export const getNonHumanImages = async (): Promise<GalleryImage[]> => {
  return nonHumanImages
}

// Legacy function for backward compatibility
export const getGalleryImages = async (type: 'human' | 'non-human'): Promise<GalleryImage[]> => {
  switch (type) {
    case 'human':
      return getHumanImages()
    case 'non-human':
      return getNonHumanImages()
    default:
      return []
  }
}
